[colors]
foreground = "#CECDC3"
background = "#100F0F"
border = "#4385BE"
selected_fg = "#100F0F"
selected_bg = "#4385BE"
selected_modifier = ["bold"]
icon_color = "#D14D41"
help_fg = "#6F6E69"
help_key_fg = "#879A39"
help_key_modifier = ["bold"]

[border]
enabled = true
style = "rounded"

[animation]
animation_type = "matrix"
speed_ms = 80
color = "#879A39"
density = 50
adaptive_quality = true
min_speed_ms = 200
