[colors]
foreground = "#ebdbb2"
background = "#282828"
border = "#d79921"
selected_fg = "#282828"
selected_bg = "#b8bb26"
selected_modifier = ["bold"]
icon_color = "#fb4934"
help_fg = "#928374"
help_key_fg = "#fe8019"
help_key_modifier = ["bold"]

[border]
enabled = true
style = "rounded"

[animation]
animation_type = "matrix"
speed_ms = 80
color = "#b8bb26"
density = 50
adaptive_quality = true
min_speed_ms = 200
