[colors]
foreground = "#8f93a2"
background = "#0f111a"
border = "#82aaff"
selected_fg = "#0f111a"
selected_bg = "#82aaff"
selected_modifier = ["bold"]
icon_color = "#f07178"
help_fg = "#464b5d"
help_key_fg = "#89ddff"
help_key_modifier = ["bold"]

[border]
enabled = true
style = "rounded"

[animation]
animation_type = "ocean"
speed_ms = 90
color = "#82aaff"
density = 50
adaptive_quality = true
min_speed_ms = 200
