[colors]
foreground = "#FCFCFA"
background = "#2D2A2E"
border = "#AB9DF2"
selected_fg = "#2D2A2E"
selected_bg = "#AB9DF2"
selected_modifier = ["bold"]
icon_color = "#FF6188"
help_fg = "#727072"
help_key_fg = "#78DCE8"
help_key_modifier = ["bold"]

[border]
enabled = true
style = "rounded"

[animation]
animation_type = "matrix"
speed_ms = 80
color = "#A9DC76"
density = 50
adaptive_quality = true
min_speed_ms = 200
